import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

/**
 * Export element as PNG image
 * @param {HTMLElement} element - Element to export
 * @param {string} filename - Output filename
 */
export async function exportAsImage(element, filename = 'gpa-report.png') {
    try {
        const canvas = await html2canvas(element, {
            backgroundColor: '#ffffff',
            scale: 2, // Higher quality
            useCORS: true,
        });

        const link = document.createElement('a');
        link.download = filename;
        link.href = canvas.toDataURL('image/png');
        link.click();

        return true;
    } catch (error) {
        console.error('Export as image failed:', error);
        return false;
    }
}

/**
 * Export element as PDF
 * @param {HTMLElement} element - Element to export
 * @param {string} filename - Output filename
 */
export async function exportAsPDF(element, filename = 'gpa-report.pdf') {
    try {
        const canvas = await html2canvas(element, {
            backgroundColor: '#ffffff',
            scale: 2,
            useCORS: true,
        });

        const imgData = canvas.toDataURL('image/png');
        const pdf = new jsPDF({
            orientation: 'portrait',
            unit: 'px',
            format: [canvas.width, canvas.height],
        });

        pdf.addImage(imgData, 'PNG', 0, 0, canvas.width, canvas.height);
        pdf.save(filename);

        return true;
    } catch (error) {
        console.error('Export as PDF failed:', error);
        return false;
    }
}

/**
 * Share report using Web Share API
 * @param {Object} data - Share data (title, text, url)
 */
export async function shareReport(data) {
    if (navigator.share) {
        try {
            await navigator.share(data);
            return true;
        } catch (error) {
            if (error.name !== 'AbortError') {
                console.error('Share failed:', error);
            }
            return false;
        }
    } else {
        // Fallback: copy to clipboard
        try {
            await navigator.clipboard.writeText(data.text);
            return true;
        } catch (error) {
            console.error('Clipboard copy failed:', error);
            return false;
        }
    }
}

/**
 * Generate report text summary
 * @param {Object} data - Report data
 * @returns {string} Formatted report text
 */
export function generateReportText(data) {
    const { courses, semesters, gpa, cgpa, totalUnits, totalPoints } = data;

    let text = '📚 UNIBEN GPA Report\n';
    text += '━━━━━━━━━━━━━━━━━━━━\n\n';

    if (gpa !== undefined) {
        text += `📊 Semester GPA: ${gpa.toFixed(2)}\n`;
        text += `📝 Total Units: ${totalUnits}\n`;
        text += `✨ Quality Points: ${totalPoints}\n\n`;
    }

    if (cgpa !== undefined) {
        text += `📈 Cumulative GPA: ${cgpa.toFixed(2)}\n\n`;
    }

    if (courses && courses.length > 0) {
        text += 'Courses:\n';
        courses.forEach((course) => {
            text += `• ${course.name}: ${course.grade} (${course.creditUnit} units)\n`;
        });
    }

    text += '\n━━━━━━━━━━━━━━━━━━━━\n';
    text += 'Generated by UNIBEN GPA Calculator';

    return text;
}
